### PR TITLE
fix: mixed shorthand and longhand class/id

### PR DESCRIPTION
**Pull request by jwise7**
## Description

prettier was failing hard when it encountered marko syntax like this: div.foo class=input.bar. the duplicated class definition created an ArrayExpression that wasn't being handled

## Motivation and Context

bugfix

## Checklist:

- [n/a] I have updated/added documentation affected by my changes.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by DylanPiercey** [comment]
@jwise7 thanks for making the PR! I think the CI is going to fail though do to formatting. Could you run `npm run format` and commit that?

**Comment by jwise7** [comment]
i did, before commiting, but forgot it had an error:

> prettier-plugin-marko@1.0.0 format
> npm run lint:eslint -- --fix && npm run lint:prettier -- --write && (fixpack || true)


> prettier-plugin-marko@1.0.0 lint:eslint
> eslint -f visualstudio . "--fix"

no problems

> prettier-plugin-marko@1.0.0 lint:prettier
> prettier '**/*{.ts,.js,.json,.md,.yml,rc}' "--write"

[error] No files matching the pattern were found: "'**/*{.ts,.js,.json,.md,.yml,rc}'".

**Comment by DylanPiercey** [comment]
@jwise7 I think the issue is our format command is not windows compatible. We need to update the `lint:prettier` to escape the quotes, like here https://github.com/marko-js/vite/blob/main/package.json#L84

**Comment by jwise7** [comment]
thanks, figured it was a windows issue, i had to comment out the husky stuff just to get that to stop giving an error message. sorry for breaking everything with windows! :D

**Comment by DylanPiercey** [comment]
No worries! I've been slowly trying to bring windows into our CI workflow since GitHub Actions actually supports it. At some point I'll setup this repo as well to run against windows in our CI to avoid stuff like this.


Looks like the CI is still failing with a TS issue though.

**Comment by jwise7** [comment]
ok, added various type checks to make it happy, i hope.

**Comment by jwise7** [comment]
added "div.foo.${bar} class=input.baz" as another fixture to increase code coverage, but that's a new breaking case. will look into it in a bit

**Comment by jwise7** [comment]
just noticed that the previous fixture i based that off of has .skip in it's name, looks like a similar but different issue to what i was fixing here

**Pull request closed without merging**
